[env:rpipico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
monitor_speed = 115200
build_flags = 
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_CDC

lib_deps =
    adafruit/Adafruit BMP3XX Library @ ^2.1.5
    adafruit/Adafruit BusIO @ ^1.17.4
    bolderflight/Bolder Flight Systems BMI088 @ ^1.0.1